source :rubygems

# gems required to run ci client/server
gem 'sinatra'
gem 'bob'
gem 'data_mapper'
gem 'data_objects'
gem 'do_postgres'

# gems required to run the i18n tests
gem 'activerecord'
gem 'activesupport'
gem 'sqlite3-ruby'
gem 'mocha'